### ISSUE TITLE
Very tiny typo

### ISSUE THREAD

**Issue by sarahkaarina-crockford** [cmi-dair/text-knnassifier#12]
Hi,

In the read me file with example code there is a small typo where the training data is defined as training_text but then called by the function KNN.fit as training_data  

Not a major issue but I just wanted to flag it for anyone trying to use the example code in the future :)

Thanks for sharing the project!

**Comment by ReinderVosDeWael** [comment]
Thanks for the feedback! This will be fixed in a moment.
